### ISSUE TITLE
鉴权失败

### ISSUE THREAD

**Issue by WithdewHua** [vicalloy/telegram-shell-bot#1]
【问题描述】
`user_id = update.effective_user.id` 类型为整型，而 `settings.ENABLED_USERS`为字符串列表，导致鉴权一直失败，建议对  `user_id` 做一个类型转换

**Comment by vicalloy** [comment]
修复了，在settings.py.sample里转了。
之前本地文件改了，漏了sample。

**Comment by justcopy** [comment]
请问这个问题修复了吗？ 好像还是会遇到这个问题。settings.py.sample 已经改成settings.py。并且tgbot token和userid都在settings.py里设置完成了。

 File "bot.py", line 29
    print(f"Unauthorized access denied for {user_id}.")

**Comment by vicalloy** [comment]
> 请问这个问题修复了吗？ 好像还是会遇到这个问题。settings.py.sample 已经改成settings.py。并且tgbot token和userid都在settings.py里设置完成了。
> 
> File "bot.py", line 29
> print(f"Unauthorized access denied for {user_id}.")

已经修复了，对应的转换在settings里做
ENABLED_USERS = os.environ.get("ENABLED_USERS", '00000')  # 设置用户id
ENABLED_USERS = set(int(e.strip()) for e in ENABLED_USERS.split(','))  # 将用户ID转换成int
