### ISSUE TITLE
Import delegator issue

### ISSUE THREAD

**Issue by MOOGAA** [vicalloy/telegram-shell-bot#10]
![IMG_20201206_110957](https://user-images.githubusercontent.com/67998406/101272592-a1e8e300-37b3-11eb-8b83-215a554c170e.jpg)

I whts the problem bud
![IMG_20201206_110957](https://user-images.githubusercontent.com/67998406/101272607-bc22c100-37b3-11eb-9390-046f1fc44b70.jpg)

**Comment by vicalloy** [comment]
You should install `delegator-py`。

**Comment by MOOGAA** [comment]
> You should install `delegator-py`。

Like

sudo apt install delegator -py
