### ISSUE TITLE
[Feature request] Split long messages

### ISSUE THREAD

**Issue by gregorst3** [vicalloy/telegram-shell-bot#15]
Hello, I have a script with long output, for the limitations imposed, some part of my script's output get lost. 
Is it possible to do something like this? 
https://github.com/python-telegram-bot/python-telegram-bot/issues/768#issuecomment-368349130

**Comment by vicalloy** [comment]
finished

**Comment by guerman5** [comment]
Hi @vicalloy 
I'm also interested in this feature. After updating the code, its running but it doesn't split the message. 
I've tested both versions, before and after the [changes](https://github.com/vicalloy/telegram-shell-bot/commit/143d84cb8f8044c1ae32cb26db14b75ec36013f0) but the outcome is the same (half of the output is lost)

could you check again?

Thanks for your time

**Comment by guerman5** [comment]
Here some test results to prove what I'm saying. 
![image](https://user-images.githubusercontent.com/49020044/201805990-a5f67af3-cee6-4667-95ba-2906150db2eb.png)
As you can see, _telegram-shell-bot_ only sends one message of lenght MAX_TASK_OUTPUT=500, i can increase that to 4096 but that is still less than the total output. The splitting is not happening.

while the benchmark does the spliting:
![image](https://user-images.githubusercontent.com/49020044/201806472-d17f434a-20c9-4848-9ad6-cb87a984c256.png)
![image](https://user-images.githubusercontent.com/49020044/201806048-a9d26f73-46cd-42a2-b6d3-24111415f7f0.png)



Thank you

**Comment by vicalloy** [comment]
@guerman5 fixed. telegram's max length is 4096 bytes. Python's len() is by char.

**Comment by guerman5** [comment]
Hi @vicalloy ,
I appreciate your attention :)

>         max_length = constants.MAX_MESSAGE_LENGTH // 2
>        while msg:
>            message.reply_text(msg[:max_length], *args, **kwargs)
>            msg = msg[max_length:]

My tests results are not successful :S

I confirm the new code is running as before,
![image](https://user-images.githubusercontent.com/49020044/203722275-26e332f3-3118-4f49-ae01-332ffed59db3.png)

The `message` is not being split by consecutive `msg` of `max_length` . Seems it is only sending the first `msg` of `"MAX_TASK_OUTPUT", 500`.
`cat /home/user/10K_lines.txt`
![image](https://user-images.githubusercontent.com/49020044/203721641-1ab1bd63-3f09-4404-9db5-2ddce6aa023d.png)
 I can increase that 500 in settings.py, but it just increases the first `msg` lenght, yet the split wont happen.
![image](https://user-images.githubusercontent.com/49020044/203723300-bd64b571-8354-4cb6-925b-b028e9d2700f.png)

Reference, using same file 10K_lines.txt:
![image](https://user-images.githubusercontent.com/49020044/203722067-42d13602-18f5-41ba-9a5c-ac8c4c3dc640.png)

**Comment by vicalloy** [comment]
@guerman5 

If you want output all message `MAX_TASK_OUTPUT` should set to a huge number `ex: 999999`.
By default, bot will only send first 3s message. 
If you want output all message, you should add `oa;`.

ex: `oa;cat poetry.lock`
