### ISSUE TITLE
tasks 值为 None

### ISSUE THREAD

**Issue by WithdewHua** [vicalloy/telegram-shell-bot#2]
【复现步骤】
- `python bot.py` 初次运行 bot 时，此时 tasks list 为空；
- 发送命令 `/tasks`；

【问题描述】
在 shell 里可以看到 `caused error "'NoneType' object is not iterable"` 的报错，查看此时 `tasks = context.user_data.get('tasks')` 值，为 None

【修改建议】
建议增加对 tasks 值的判断

另外，提一下拼写错误，README 中 usage 一节的第一点中存在多处错误，以及 `bot.py` 中 `start` 函数中的 `shell commend`

**Comment by vicalloy** [comment]
已修复
